title: project AI
description: This repository holds few Machine Learning projects
    
remote_theme: pmarsceill/just-the-docs

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
