title: project AI
description: This repository holds few Machine Learning projects

#optional variables
show_downloads: ["true"]

plugins:
 - jekyll-feed
 - jekyll-redirect-from
 - jekyll-seo-tag
 - jekyll-sitemap
 - jekyll-avatar
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache

theme: jekyll-theme-dinky
